name: Install Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  install:
    name: CMake install
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build g++ pkg-config

      - name: Configure
        run: |
          cmake -S . -B build -G Ninja -DINKY_ENABLE_LINUX_GPIOD=OFF

      - name: Build
        run: |
          cmake --build build

      - name: Install
        run: |
          cmake --install build --prefix "$PWD/stage"
