name: QA

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Linting & Spelling
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: '3.11'

      - name: Run Quality Assurance
        run: |
          uv run make qa

      - name: Run Code Checks
        run: |
          uv run make check

      - name: Run Pre-Commit
        run: |
          uv run pre-commit run --all-files
