name: Tests

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test (Python ${{ matrix.python }})
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
    strategy:
      matrix:
        python: ['3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          python-version: ${{ matrix.python }}

      - name: Run Tests
        run: |
          uv run make pytest

      - name: Coverage
        if: ${{ matrix.python == '3.9' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          uvx coveralls --service=github
